services:
  db:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - buffet-pos-network
    restart: on-failure

volumes:
  db-data:
    driver: local
networks:
  buffet-pos-network:
    driver: bridge
