definitions:
  models.Role:
    enum:
    - manager
    - employee
    type: string
    x-enum-varnames:
    - Manager
    - Employee
  requests.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  requests.UserRegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  responses.UserLoginResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        $ref: '#/definitions/models.Role'
      token:
        type: string
    type: object
  responses.UserRegisterResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is the BuffetPOS API documentation.
  title: BuffetPOS API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Check user credentials and return user data.
      parameters:
      - description: User login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserLoginResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: User login.
      tags:
      - User
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user.
      parameters:
      - description: User register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserRegisterResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: User register (Employee Role by default)
      tags:
      - User
swagger: "2.0"
