definitions:
  models.Role:
    enum:
    - manager
    - employee
    type: string
    x-enum-varnames:
    - Manager
    - Employee
  requests.AddTableRequest:
    properties:
      tableName:
        type: string
    required:
    - tableName
    type: object
  requests.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  requests.UserRegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  responses.AddTableResponse:
    properties:
      message:
        type: string
    type: object
  responses.FindTableResponse:
    properties:
      accessCode:
        type: string
      createdAt:
        type: string
      id:
        type: string
      isAvailable:
        type: boolean
      qrcode:
        type: string
      tableName:
        type: string
      updatedAt:
        type: string
    type: object
  responses.UserLoginResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        $ref: '#/definitions/models.Role'
      token:
        type: string
    type: object
  responses.UserRegisterResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is the BuffetPOS API documentation.
  title: BuffetPOS API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Check user credentials and return user data.
      parameters:
      - description: User login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserLoginResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: User login.
      tags:
      - User
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user.
      parameters:
      - description: User register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserRegisterResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: User register (Employee Role by default)
      tags:
      - User
  /manage/tables:
    post:
      consumes:
      - application/json
      description: Add a new table.
      parameters:
      - description: Add Table request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.AddTableRequest'
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.AddTableResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Add Table
      tags:
      - Manage
  /manage/tables/{id}:
    get:
      consumes:
      - application/json
      description: Find table by ID.
      parameters:
      - description: Table ID
        in: path
        name: id
        required: true
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.FindTableResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Find Table By ID
      tags:
      - Manage
swagger: "2.0"
